services:
  graphzep-server-test:
    build:
      context: .
      dockerfile: Dockerfile
      target: server-builder  # Use builder stage for tests
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - NEO4J_URI=bolt://neo4j-test:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=testpassword
    depends_on:
      neo4j-test:
        condition: service_healthy
    networks:
      - test-network
    command: ["npm", "test"]
    volumes:
      - ./server/src:/app/server/src
      - ./src:/app/src

  neo4j-test:
    image: neo4j:5.26.2
    healthcheck:
      test: ["CMD-SHELL", "cypher-shell -u neo4j -p testpassword 'RETURN 1' || exit 1"]
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 20s
    environment:
      - NEO4J_AUTH=neo4j/testpassword
      - NEO4J_PLUGINS=["apoc"]
    networks:
      - test-network
    tmpfs:
      - /data  # Use tmpfs for faster test execution

  # Integration test runner
  integration-tests:
    build:
      context: .
      dockerfile: Dockerfile
      target: server-builder
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - NEO4J_URI=bolt://neo4j-test:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=testpassword
    depends_on:
      graphzep-server-test:
        condition: service_completed_successfully
    networks:
      - test-network
    command: |
      sh -c "
        echo 'Running integration tests...'
        npm run test
        echo 'Testing server endpoints...'
        curl -f http://graphzep-server-test:3000/healthcheck || exit 1
      "
    volumes:
      - ./server/src:/app/server/src
      - ./src:/app/src

networks:
  test-network:
    driver: bridge